apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.deploy.projectName }}
  name: {{ .Values.deploy.projectName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.deploy.projectName }}
  template:
    metadata:
      labels:
        app: {{ .Values.deploy.projectName }}
    spec:
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
      containers:
        - name: {{ .Values.deploy.projectName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ .Values.deploy.projectName }}-secret
            - configMapRef:
                name: {{ .Values.deploy.projectName }}-env
          ports:
            - containerPort: {{ .Values.deploy.containerPort }}
          tty: true
          volumeMounts:
            - mountPath: /mnt/sqlite_db
              name: work-tracker-db-pv

      volumes:
        - name: work-tracker-db-pv
          persistentVolumeClaim:
            claimName: work-tracker-db-pv-claim
